image: node:9

variables:
  KUBERNETES_VERSION: 1.8.6
  HELM_VERSION: 2.6.1

before_script:
  - npm i -g lerna
  - lerna bootstrap --ci

cache:
  paths:
  - node_modules/
  - apps/toast-web/node_modules/
  - apis/toast-core/node_modules/

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - lerna run test

build:
  stage: build
  image: docker:stable-git
  services:
  - docker:stable-dind
  script:
    - lerna run --scope=toast-core containerize

deploy_stage:
  stage: deploy
  script:
    - echo "Deploy stage"
  environment:
    name: stage
    url: https://stage.toastcooking.app
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "deb http://packages.cloud.google.com/apt cloud-sdk-jessie main" | tee /etc/apt/sources.list.d/google-cloud-sdk.list
    - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    - apt-get update && apt-get install google-cloud-sdk
    - echo "Deploy prod"
  environment:
    name: production
    url: https://toastcooking.app
  when: manual
  only:
  - master
