image: gforrest/docker-gitlab-dind-node:latest

variables:
  DOCKER_DRIVER: overlay
  IMAGE_NAME: toast-core
  IMAGE_REPO_SOURCE: us.gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME:latest

stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    - lerna bootstrap
  script:
    - lerna run test
  only:
    - branches

build:
  stage: build
  services:
    - docker:dind
  before_script:
    - export DOCKER_HOST=tcp://localhost:2375
    # Write our GCP service account private key into a file
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - lerna bootstrap
  script:
    - docker login -u _json_key -p "$(cat ${HOME}/gcloud-service-key.json)" https://us.gcr.io
    - cd apis/toast-core
    - npm run containerize
    - docker tag toast-core $IMAGE_REPO_SOURCE
    - docker push $IMAGE_REPO_SOURCE
  only:
    - master

deploy:
  stage: deploy
  variables:
    APP_PORT: 4000
    NAMESPACE: stage
  before_script:
    - export DOCKER_HOST=tcp://localhost:2375
    # Write our GCP service account private key into a file
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $GCLOUD_PROJECT_ID
    - gcloud config set compute/zone $GCLOUD_COMPUTE_ZONE
    - source ops/scripts/deploy_functions.sh
  script:
    - deploy
