image: alpine:latest

variables:
  KUBERNETES_VERSION: 1.8.6

stages:
  - test
  - containerize
  - deploy

test:
  stage: test
  image: registry.gitlab.com/a-type/docker-gitlab-dind-node:latest
  before_script: 
    - npm i -g lerna
  script:
    - lerna run test
  only:
    - branches

containerize:
  stage: containerize
  image: registry.gitlab.com/a-type/docker-gitlab-dind-node:latest
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    # Write our GCP service account private key into a file
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - docker login -u _json_key --password-stdin https://us.gcr.io < ${HOME}/gcloud-service-key.json
    - npm i -g lerna
  script:
    - lerna run --scope=toast-core containerize
  only:
    - master

deploy:
  stage: deploy
  image: registry.gitlab.com/a-type/docker-gitlab-dind-node:latest
  variables:
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: toast-core
    IMAGE_REPO_SOURCE: us.grc.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME:latest
    APP_PORT: 4000
  before_script:
    # Write our GCP service account private key into a file
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $GCLOUD_PROJECT_ID
    - gcloud config set compute/zone $GCLOUD_COMPUTE_ZONE
    - source ops/scripts/deploy_functions.sh
  script:
    - deploy
