image: us.gcr.io/toast-cooking-0/docker-gitlab-dind-node:latest

variables:
  DOCKER_DRIVER: overlay
  IMAGE_NAME: toast-core
  IMAGE_TAG: $CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA
  IMAGE_REPO_SOURCE: us.gcr.io/$GCLOUD_PROJECT_ID/$IMAGE_NAME:$CI_COMMIT_REF_SLUG_$CI_COMMIT_SHA
  TILLER_NAMESPACE: "kube-system"
  CLUSTER_NAME: toast-primary

stages:
  - test
  - build
  - deploy

test:
  stage: test
  before_script:
    - source ops/scripts/build_functions.sh
    - install
  script:
    - test
  only:
    - branches

build:
  stage: build
  services:
    - docker:dind
  before_script:
    - export DOCKER_HOST=tcp://localhost:2375
    # Write our GCP service account private key into a file
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - source ops/scripts/build_functions.sh
    - install
  script:
    - build
  only:
    - master

deploy:
  stage: deploy
  variables:
    APP_PORT: 4000
    NAMESPACE: toast-prod
    ENV_SUFFIX: -prod
  before_script:
    - export DOCKER_HOST=tcp://localhost:2375
    # Write our GCP service account private key into a file
    - echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud config set project $GCLOUD_PROJECT_ID
    - gcloud config set compute/zone $GCLOUD_COMPUTE_ZONE
    - gcloud container clusters get-credentials $CLUSTER_NAME --zone us-east1-b --project $GCLOUD_PROJECT_ID
    - kubectl config current-context
    - source ops/scripts/deploy_functions.sh
  script:
    - deploy
