steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install dependencies'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Test'
    args: ['run', 'test']

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build'
    args: ['run', 'build']
    env:
      - 'BUILD_ID=$BUILD_ID'

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install server dependencies'
    args: ['install']
    dir: 'server'

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build server'
    args: ['run', 'build']
    env:
      - 'BUILD_ID=$BUILD_ID'
    dir: 'server'

  # Build snapshot images and push them to Cloud Registry

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build deployable image (commit tag)'
    args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/toast-web:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push deployable image (commit tag)'
    args: ['push', 'us.gcr.io/$PROJECT_ID/toast-web:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build deployable image (latest tag)'
    args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/toast-web:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push deployable image (latest tag)'
    args: ['push', 'us.gcr.io/$PROJECT_ID/toast-web:latest']

  # Deployment

  - name: 'gcr.io/toast-cooking-0/helm'
    id: 'Generate a new Ingress, Service and Deployment'
    args:
      - 'upgrade'
      - '--install'
      - '--set'
      - 'image.tag=$SHORT_SHA'
      - 'toast-web'
      - './charts/toast-web'
      - '--namespace=production'
      - '--tiller-namespace=kube-system'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=toast-primary'

images:
  - 'us.gcr.io/$PROJECT_ID/toast-web:$SHORT_SHA'
  - 'us.gcr.io/$PROJECT_ID/toast-web:latest'
