export const CONTENT_WIDTH = 600;
export const LARGE_PADDING_LEFT = 40;
export const RIGHT_MARGIN_WIDTH = 400;
export const LARGE_BREAKPOINT =
  CONTENT_WIDTH + LARGE_PADDING_LEFT + RIGHT_MARGIN_WIDTH;
