apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "toast-core.fullname" . }}
  labels:
    app: {{ template "toast-core.name" . }}
    chart: {{ template "toast-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "toast-core.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "toast-core.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.application.port }}
              protocol: TCP
          volumeMounts:
            - name: service-account-secret
              mountPath: /var/secrets/service-account
            - name: firebase-service-account-secret
              mountPath: /var/secrets/firebase-service-account
          env:
            - name: NEO4J_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.creds.secretName }}
                  key: user
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.creds.secretName }}
                  key: password
            - name: NEO4J_BOLT_HOST
              value: {{ .Values.db.hosts.bolt }}
            - name: PORT
              value: '{{ .Values.application.port }}'
            - name: GCLOUD_MEDIA_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.application.storage.bucketNameSecretName }}
                  key: bucket
            - name: GCLOUD_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.application.storage.projectIdSecretName }}
                  key: id
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/service-account/key.json
            - name: RECIPE_SCRAPER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.services.recipeScraperSecretName }}
                  key: secret
            - name: FIREBASE_SERVICE_ACCOUNT_KEY_FILE
              value: '/var/secrets/firebase-service-account/key.json'
            - name: FIREBASE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.firebase.configSecretName }}
                  key: databaseUrl
            - name: FIREBASE_MESSAGING_SERVER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.firebase.configSecretName }}
                  key: messagingServerKey
            - name: FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.firebase.configSecretName }}
                  key: messagingSenderId
      volumes:
        - name: tls-secret
          secret:
            secretName: {{ .Values.ingress.tls.secretName }}
        - name: service-account-secret
          secret:
            secretName: {{ .Values.application.service.serviceAccountSecretName }}
        - name: firebase-service-account-secret
          secret:
            secretName: {{ .Values.firebase.serviceAccountSecretName }}
