{{- $fullName := include "toast-core.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $fullName }}-ingress"
  labels:
    app: {{ template "toast-core.name" . }}
    chart: {{ template "toast-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIp }}
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: {{ .Values.ingress.tls.secretName }}
  backend:
    serviceName: {{ $fullName }}
    servicePort: https
