apiVersion: v1
kind: Service
metadata:
  name: {{ template "toast-core.fullname" . }}
  labels:
    app: {{ template "toast-core.name" . }}
    chart: {{ template "toast-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: {{ .Values.application.port }}
      protocol: TCP
      name: https
  selector:
    app: {{ template "toast-core.name" . }}
    release: {{ .Release.Name }}
