# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: us.gcr.io/toast-cooking-0/toast-core
  tag: latest
  pullPolicy: IfNotPresent
ingress:
  staticIp: "toast-primary-ingress"
  path: /
  tls:
    secretName: toast-tls
service:
  name: toast-core
  type: NodePort
  externalPort: 80
  internalPort: 4000
webService:
  name: toast-web
  type: NodePort
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /ping
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
db:
  creds:
    secretName: neo4j-neo4j-secrets
  hosts:
    bolt: bolt+routing://neo4j-neo4j-core-0.neo4j-neo4j.production.svc.cluster.local:7687
application:
  storage:
    bucketName: toast-media-prod
    projectId: toast-cooking-0
  services:
    planning:
      host: http://toast-planning.production.svc.cluster.local
    scanning:
      host: http://toast-scanning.production.svc.cluster.local
firebase:
  configSecretName: firebase-config
  serviceAccountSecretName: firebase-prod-service-account
  serviceAccountSecretKey: key.json
projectId: toast-cooking-0
