# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: us.gcr.io/toast-cooking-0/toast-web
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: toast-web
  type: NodePort
  externalPort: 80
  internalPort: 4040
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
ingress:
  staticIp: 'toast-primary-ingress'
  path: /
  tls:
    secretName: toastcooking-app-tls-prod
